
title: Lev's Blog
description: some humble pursuits. research and personal curiosities intertwined.

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-mathjax

mathjax:
  enable: true
  content: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
